### ISSUE TITLE
Can't add new pub to pinned pubs on a page.

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1336]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Under a pub block, there's the option to pin pubs to a section
2. When I try to drag and drop a pub that's not yet pinned (from left to right now), it's not added to the pinned column.
...

### What did you expect to happen?
I would expect that I could add new pubs to the pinned section. Even if there exceed the number of pubs that'll be shown (ie I drag a sixth pub to a block that will only show five), that I could still add new pubs as before. 

### What URL can we use to see the issue?
https://commonplace.knowledgefutures.org/dash/pages/home

### What browser/operating system were you using?
Chrome/DuckDuckGo Extension, and macOS Big Sur

===

**Comment by gabestein** [comment]
Resolved by c23ec9

**Comment by sarah-tonin** [comment]
Can we open this back up? The problem still exists on my end.

**Comment by sarah-tonin** [comment]
In addition, it happens in Safari as well, so maybe there's something wrong with my account?

**Comment by sarah-tonin** [comment]
Maybe this will help? It's a screen capture of me trying to drag and drop unsuccessfully. Thank you !!
[pubsNotDragNorDrop.zip](https://github.com/pubpub/pubpub/files/6336769/pubsNotDragNorDrop.zip)

**Comment by idreyn** [comment]
Ah — sorry for the confusion here and for not reading your comment carefully; I was conflating this with another issue. We changed the way this interaction works, and you can now click on Pubs to add them to the end of the pinned list, and then drag and drop to reorder them once they're already in there.

**Comment by sarah-tonin** [comment]
Ah! Thanks, Ian!
